//! Hybrid finality-vote signature verification — snorkel's own.
//!
//! Rostro validators sign finality votes with a hybrid scheme:
//! **ed25519 + SLH-DSA-SHA2-128s, both must verify**. ed25519 alone
//! falls to a cryptographically relevant quantum computer; SLH-DSA is
//! hash-based and does not. Requiring both means forging a vote needs
//! a break of each, so a CRQC cannot manufacture an alternate
//! finalized history.
//!
//! ## Deliberately independent
//!
//! This is a verify-only reimplementation, NOT a dependency on
//! Rostro's `rostro-hybrid-sig`. The snorkel stays a self-contained
//! codebase that builds from crates.io alone. Both primitives come
//! from the same upstream crates the chain uses:
//!
//! - `ed25519-dalek` 2.x — stock from crates.io.
//! - `slh-dsa` 0.1.0 — vendored at `external/slh-dsa`. Vendoring is
//!   forced, not preferred: upstream 0.1.0 pins a PRE-RELEASE of the
//!   `signature` trait crate, which Cargo cannot unify with the stable
//!   `signature 2.x` that `ed25519-dalek` resolves. Stock versions of
//!   the two crates cannot coexist in one graph, and a hybrid scheme
//!   needs both. Rostro hit the same wall; see
//!   `external/slh-dsa/VENDOR-SNORKEL.md`. The copy carries two
//!   documented build-only changes and no logic changes.
//!
//! The snorkel never signs and never generates keys, so none of that
//! surface is reproduced — only verification.
//!
//! ## Drift protection
//!
//! Independence means the wire format could silently diverge. The KAT
//! test at the bottom pins a real (public key, message, signature)
//! triple generated by the chain's own signer. If Rostro ever changes
//! the domain string, the ed25519 preimage framing, the SLH context
//! binding, or the byte layout, that test fails here rather than the
//! snorkel quietly rejecting every genuine justification in
//! production.
//!
//! ## Wire layout (frozen)
//!
//! ```text
//! public key  64 B  = ed25519 pk (32) ‖ SLH-DSA pk (32)
//! signature 7920 B  = ed25519 sig (64) ‖ SLH-DSA sig (7856)
//! ```
//!
//! The two halves bind the domain differently, and both bindings
//! matter:
//!
//! ```text
//! ed25519 : verify_strict( 0x00 ‖ len(domain) ‖ domain ‖ msg )
//! SLH-DSA : try_verify_with_context( msg, context = domain )
//! ```

use ed25519_dalek::{Signature as EdSignature, VerifyingKey as EdVerifyingKey};
use slh_dsa::{Sha2_128s, Signature as SlhSignature, VerifyingKey as SlhVerifyingKey};

use crate::verify::HybridVerify;

/// ed25519 public-key length.
pub const ED25519_PK_BYTES: usize = 32;
/// ed25519 signature length.
pub const ED25519_SIG_BYTES: usize = 64;
/// SLH-DSA-SHA2-128s public-key length (FIPS 205 table 2).
pub const SLH_PK_BYTES: usize = 32;
/// SLH-DSA-SHA2-128s signature length (FIPS 205 table 2).
pub const SLH_SIG_BYTES: usize = 7856;

/// Hybrid public key: `ed25519 pk ‖ SLH-DSA pk`.
pub const HYBRID_PK_BYTES: usize = ED25519_PK_BYTES + SLH_PK_BYTES;
/// Hybrid signature: `ed25519 sig ‖ SLH-DSA sig`.
pub const HYBRID_SIG_BYTES: usize = ED25519_SIG_BYTES + SLH_SIG_BYTES;

/// Domain-separated preimage the ed25519 half signs over:
/// `0x00 ‖ len(domain) as u8 ‖ domain ‖ msg`.
///
/// The leading `0x00` is a scheme-version byte and the explicit length
/// prevents a domain/message boundary ambiguity. Domains longer than
/// 255 bytes are rejected (`None`) rather than truncated.
fn ed25519_preimage(domain: &[u8], msg: &[u8]) -> Option<Vec<u8>> {
    let len = u8::try_from(domain.len()).ok()?;
    let mut out = Vec::with_capacity(2 + domain.len() + msg.len());
    out.push(0u8);
    out.push(len);
    out.extend_from_slice(domain);
    out.extend_from_slice(msg);
    Some(out)
}

/// Verify-only hybrid checker. Stateless; construct freely.
#[derive(Clone, Copy, Debug, Default)]
pub struct HybridVerifier;

impl HybridVerify for HybridVerifier {
    /// `true` only if BOTH halves verify. Any malformed input — wrong
    /// length, non-canonical key, unparseable signature — is `false`,
    /// never a panic: every byte here came from a courier we treat as
    /// hostile.
    fn verify(&self, public: &[u8], domain: &[u8], msg: &[u8], sig: &[u8]) -> bool {
        if public.len() != HYBRID_PK_BYTES || sig.len() != HYBRID_SIG_BYTES {
            return false;
        }
        let (ed_pk_bytes, slh_pk_bytes) = public.split_at(ED25519_PK_BYTES);
        let (ed_sig_bytes, slh_sig_bytes) = sig.split_at(ED25519_SIG_BYTES);

        let Ok(ed_pk_arr) = <[u8; ED25519_PK_BYTES]>::try_from(ed_pk_bytes) else {
            return false;
        };
        let Ok(ed_pk) = EdVerifyingKey::from_bytes(&ed_pk_arr) else {
            return false;
        };
        let Ok(ed_sig_arr) = <[u8; ED25519_SIG_BYTES]>::try_from(ed_sig_bytes) else {
            return false;
        };
        let ed_sig = EdSignature::from_bytes(&ed_sig_arr);

        let Some(preimage) = ed25519_preimage(domain, msg) else {
            return false;
        };
        // Strict: rejects small-order / non-canonical points, matching
        // the signer side exactly.
        if ed_pk.verify_strict(&preimage, &ed_sig).is_err() {
            return false;
        }

        // ed25519 is ~100x cheaper, so it gates first and garbage never
        // reaches the hash-based half.
        let Ok(slh_pk) = SlhVerifyingKey::<Sha2_128s>::try_from(slh_pk_bytes) else {
            return false;
        };
        let Ok(slh_sig) = SlhSignature::<Sha2_128s>::try_from(slh_sig_bytes) else {
            return false;
        };
        slh_pk.try_verify_with_context(msg, domain, &slh_sig).is_ok()
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::indexing_slicing)]
mod tests {
    use super::*;
    use crate::verify::FINALITY_VOTE_DOMAIN;
    use crate::wire::from_hex;

    /// A real (pk, msg, sig) triple produced by the CHAIN's signer
    /// (`rostro-hybrid-sig`, seed `[0x42; 32]`). Proves this
    /// independent implementation agrees with the one validators use.
    fn kat() -> (Vec<u8>, Vec<u8>, Vec<u8>) {
        let raw = include_str!("../vectors/hybrid_finality_v1.txt");
        let mut lines = raw.lines();
        let pk = from_hex(lines.next().unwrap().trim()).unwrap();
        let msg = from_hex(lines.next().unwrap().trim()).unwrap();
        let sig = from_hex(lines.next().unwrap().trim()).unwrap();
        (pk, msg, sig)
    }

    #[test]
    fn kat_vector_has_the_frozen_lengths() {
        let (pk, _, sig) = kat();
        assert_eq!(pk.len(), HYBRID_PK_BYTES);
        assert_eq!(sig.len(), HYBRID_SIG_BYTES);
    }

    /// The load-bearing test: a signature made by the chain verifies
    /// under our own independent implementation.
    #[test]
    fn accepts_a_real_chain_signature() {
        let (pk, msg, sig) = kat();
        assert!(
            HybridVerifier.verify(&pk, FINALITY_VOTE_DOMAIN, &msg, &sig),
            "independent verifier rejected a genuine chain signature — \
             the wire format or domain has drifted"
        );
    }

    #[test]
    fn rejects_wrong_domain() {
        let (pk, msg, sig) = kat();
        assert!(!HybridVerifier.verify(&pk, b"rostro/wrong-domain/v1", &msg, &sig));
    }

    #[test]
    fn rejects_tampered_message() {
        let (pk, mut msg, sig) = kat();
        msg[0] ^= 0x01;
        assert!(!HybridVerifier.verify(&pk, FINALITY_VOTE_DOMAIN, &msg, &sig));
    }

    /// Flipping a bit in the ed25519 half must fail even though the
    /// SLH half is untouched — proves both halves are actually checked.
    #[test]
    fn rejects_tampered_ed25519_half() {
        let (pk, msg, mut sig) = kat();
        sig[0] ^= 0x01;
        assert!(!HybridVerifier.verify(&pk, FINALITY_VOTE_DOMAIN, &msg, &sig));
    }

    /// The PQ half is the whole point: a valid ed25519 half must not
    /// rescue a corrupted SLH-DSA half.
    #[test]
    fn rejects_tampered_slh_half() {
        let (pk, msg, mut sig) = kat();
        sig[ED25519_SIG_BYTES + 16] ^= 0x01;
        assert!(!HybridVerifier.verify(&pk, FINALITY_VOTE_DOMAIN, &msg, &sig));
    }

    #[test]
    fn rejects_wrong_lengths() {
        let (pk, msg, sig) = kat();
        assert!(!HybridVerifier.verify(&pk[..63], FINALITY_VOTE_DOMAIN, &msg, &sig));
        assert!(!HybridVerifier.verify(&pk, FINALITY_VOTE_DOMAIN, &msg, &sig[..7919]));
        assert!(!HybridVerifier.verify(&[], FINALITY_VOTE_DOMAIN, &msg, &sig));
    }

    #[test]
    fn oversized_domain_is_rejected_not_truncated() {
        let (pk, msg, sig) = kat();
        assert!(!HybridVerifier.verify(&pk, &[0x61u8; 256], &msg, &sig));
    }
}
